### ISSUE TITLE
Bug: add more settings in eform.properties when exporting eform 

### ISSUE THREAD

**Issue by oscar-admin** [oscaremr/oscar#275]
Need to add these settings in eform.properties in order to upload in eform portal.
eform.name=
eform.desc=
eform.date=
eform.ver=
eform.creator=
eform.htmlFilename=
eform.htmlImages=
eform.keywords=

**Comment by oscar-admin** [comment]
Still not working...please see my email.

**Comment by huchengyi** [comment]
now it work

**Comment by oscar-admin** [comment]
The image did not show up after uploading to eformportal.

**Comment by huchengyi** [comment]
the image can show up now
