### ISSUE TITLE
Bug: percentage service code 

### ISSUE THREAD

**Issue by oscar-admin** [oscaremr/oscar#276]
Request from client 1185. Estimated time 2hours.
Create an invoice with service code A $10.00 , unit 2, service code B $20.00, unit 1, percentage service code C (50%) unit 1. It should display $10.00 x 0.5 x 2, $20.00 x 0.5 x 1 as options with radio box to check. So the user can click on any of them to add percentage fee to total amount.

**Comment by zhoulingmin** [comment]
It's not clear. It now displays two checkboxs to check, just change checkboxs to radio box?

**Comment by annie-zhou** [comment]
Sorry, still keep checkbox.
The current version has two check boxes, but they are $10.00 x 0.5 x 1, $20.00 x 0.5 x 1. We need to have each service code unit number replace the unit numver from that percentage code which is 1 in our example.

**Comment by annie-zhou** [comment]
My mistake, if the percentage service code's unit is 3, we should display : $10.00 x 0.5 x 3 x 2, $20.00 x 0.5 x 3 x 1 .
