### ISSUE TITLE
[New Feature] -P3 : A233 service code customization

### ISSUE THREAD

**Issue by oscar-admin** [oscaremr/oscar#285]
The request from client 1037. The estimated hours is 8 hours. The deadline is March 13, 2015.

Have cme_js=eyeform_poc in oscar.properties.
Create a billing with service codes A234A/G435A and other codes. Before saving billing, should check the patient's billing history. If there is service code A233A billed before and is eligible(meet the 3 conditions described below), replace A234A/G435A with A233A, leave other service code as is.

A233A code eligible conditions:
1. A233A code can only be billed 1times a year (assuming same diagnostic code)
2. A233A can be billed 2 times a year if different diagnostic codes
3. A233A should not be used within 3 month of A235A or A253A codes
If A233A can be billed again, means it is eligible.

Should check A233A from Macro and regular billing.

The description from the doctor:---------------------
When A234A/G435A codes (always together) are used for "follow-up" pts....oscar checks to see if A233A has been billed within a year (same diagnosis) or within 6 months (different diagnostic code)....if pt is A233A "eligible"...then oscar deletes the A234A/G435A billing request, and bills as A233A automatically instead.

**Comment by oscar-admin** [comment]
Please don't work on this one, still need approval from the doctor..

**Comment by zhoulingmin** [comment]
Macro billing didn't save service date in EyeformMacro table, how to check if A233A is eligible or not to the macro billing?

**Comment by oscar-admin** [comment]
You can find service date in billing_on_item. The default service date for macro is today's date.
Annie
