### ISSUE TITLE
[Bug] -P1: could not print pdf from eform

### ISSUE THREAD

**Issue by oscar-admin** [oscaremr/oscar#316]
The client ID: 1494, the estimated time is 2Hr, the deadline March 06, 2015.
OpenJDK6 or 7, 64bit ubuntu server.
Create a new eform with pdf button from eform generator. Open this eform, print pdf. Got 0 size.

**Comment by zhoulingmin** [comment]
I need right to access to the server including login and SSH, it should be configuration issue.  
Maybe WKHTMLTOPDF_COMMAND isn't valid in that server.

**Comment by zhoulingmin** [comment]
Using a new version of wkhtmltopdf fixed this issue:
Here's some instruction:
$ cd /tmp/
$ wget -q http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
$ dpkg -x wkhtmltox-0.12.2.1_linux-trusty-amd64.deb ~/wkhtmltool/
